In [3]:
import numpy as np


In [2]:
%pwd

'C:\\Users\\shshin\\Documents\\jupyter\\data_test'

In [1]:
pip install jupyter_contrib_nbextensions && jupyter contrib nbextension install

Note: you may need to restart the kernel to use updated packages.Collecting jupyter_contrib_nbextensions
  Using cached jupyter_contrib_nbextensions-0.7.0.tar.gz (23.5 MB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached jupyter_contrib_core-0.4.2.tar.gz (17 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Using cached jupyter_highlight_selected_word-0.2.0-py2.py3-none-any.whl (11 kB)
  Using cached jupyter_nbextensions_configurator-0.6.1.tar.gz (481 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
     ---------------------------------------- 3.9/3.9 MB 31.1 MB/s eta 0:00:00
     -------------------------------------- 155.4/155.4 kB 9.1 MB/s eta 0:00:00
  Created wheel for jupyter_contrib_nbextensions: filename=jupyter_contrib_nbextensions-0.7.0-py2.py3-none-any.whl size=23428787 sha256=26f095148f714a808

  error: subprocess-exited-with-error
  
  python setup.py bdist_wheel did not run successfully.
  exit code: 1
  
  [95 lines of output]
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\jupyter_nbextensions_configurator
  copying src\jupyter_nbextensions_configurator\application.py -> build\lib\jupyter_nbextensions_configurator
  copying src\jupyter_nbextensions_configurator\__init__.py -> build\lib\jupyter_nbextensions_configurator
  running egg_info
  writing src\jupyter_nbextensions_configurator.egg-info\PKG-INFO
  writing dependency_links to src\jupyter_nbextensions_configurator.egg-info\dependency_links.txt
  writing entry points to src\jupyter_nbextensions_configurator.egg-info\entry_points.txt
  writing requirements to src\jupyter_nbextensions_configurator.egg-info\requires.txt
  writing top-level names to src\jupyter_nbextensions_configurator.egg-info\top_level.txt
  reading manifest file 'src\jupyter_nbextensi

In [4]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [5]:
np.random.seed(0)

In [6]:
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

In [7]:
x3.ndim

3

In [8]:
x3.shape

(3, 4, 5)

In [9]:
x3.size

60

In [10]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [11]:
x3.dtype

dtype('int32')

In [12]:
x3.itemsize

4

In [13]:
x3.nbytes

240

In [14]:
x3 = np.random.randint(10, size=(3, 4, 5), dtype='int64')

In [15]:
x3.itemsize

8

In [16]:
x3.nbytes

480

In [17]:
x1

array([5, 0, 3, 3, 7, 9])

In [18]:
x1[0]

5

In [19]:
x1[4]

7

In [20]:
x1[-1]

9

In [21]:
x1[-2]

7

In [22]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [23]:
x2[0, 0]

3

In [24]:
x2[2, 0]

1

In [25]:
x2[2, -1]

7

In [26]:
x2[0, 0] = 12

In [27]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [28]:
x1[0] = 3.1415

In [29]:
x1

array([3, 0, 3, 3, 7, 9])

In [30]:
x = np.arange(10)

In [31]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
x[:5]

array([0, 1, 2, 3, 4])

In [33]:
x[5:]

array([5, 6, 7, 8, 9])

In [34]:
x[4:7]

array([4, 5, 6])

In [35]:
x[::2]

array([0, 2, 4, 6, 8])

In [36]:
x[1::2]

array([1, 3, 5, 7, 9])

In [37]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
l = [1,2,3,4,5]


In [39]:
l[:2]

[1, 2]

In [40]:
l

[1, 2, 3, 4, 5]

In [41]:
grid = np.arange(16).reshape((4,4,))

In [42]:
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [43]:
def compute_reciprocals(values):
    output = np.empty(len(values))
    
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        
    return output


In [45]:
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([0.25      , 0.33333333, 1.        , 0.11111111, 0.11111111])

In [46]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

2.13 s ± 53.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
